### PR TITLE
[PR] Changing UI to look like Figma

### PR DESCRIPTION
**Pull request by LuchoTurtle**
this should only be merged after #2

This PR changes the look of the UI following Figma guidelines showcased in https://www.figma.com/file/WrpkKGJNYZbeCzMRDVtvQLbC/dwyl-app?node-id=1427-3995&t=rfnjWXLzpiyhJmjT-0.

### CODE REVIEW

**Comment by LuchoTurtle** [comment]
Still in-progress. The only feature that's missing is the TextField expanding to cover the rest of the pages.
I'm having errors of overflow of X pixels like https://stackoverflow.com/questions/49480051/flutter-dart-exceptions-caused-by-rendering-a-renderflex-overflowed. However I'm having some trouble getting this to work properly.

I tried following the instructions in https://github.com/dwyl/app/issues/303 but no luck so far :/. The scenario on this issue is a bit different because there are no other elements shared within the page.

**Comment by nelsonic** [comment]
@LuchoTurtle while it's _good_ that you are attempting to faithfully replicate the Figma wireframe/layout,
I'd encourage you to always ask: "***Why***?" 
i.e: "**_Why_ are we expanding the `TextField` to occupy the whole screen?**" 

Definitely capture your attempts/progress in the issue: https://github.com/dwyl/app/issues/303
But ultimately the `Capture` screen will be re-worked very soon and will be a totally separate screen.
It will re-use the interface of the `Edit` screen which as discussed in https://github.com/dwyl/mvp/issues/214 will be separate from the "Home" page of the `App`. 
It just _looks_ like we are "pushing down" the existing `items` when we enter `Capture` mode.
But in fact we will want a seamless transition. 

More detail in: https://github.com/dwyl/app/issues/329 ⏳

**Comment by LuchoTurtle** [comment]
@nelsonic this should now be mergeable and ready for review.
Again, only merge this after #2 is merged, as this branch is branched off from https://github.com/dwyl/flutter-bloc-tutorial/pull/2.

**Comment by nelsonic** [comment]
@LuchoTurtle please rebase on `main` when you have a few mins and re-assign to me. 🙏

**Comment by LuchoTurtle** [comment]
All done.

**Review by nelsonic — CHANGES_REQUESTED** [review]
@LuchoTurtle the write-up is good. 👍 
However running the App in the iOS Simulator it still feels "unpolished" ... 📱 

That transition between the "Home" Screen an the `Item` Input is quite jarring. 😵

https://user-images.githubusercontent.com/194400/229280853-773d2367-59af-4207-bca6-48ffe6f3116e.mp4
Would prefer to **_completely_ remove** the transition than have this complete "page refresh" effect. 

Buttons for "toggling" the `item` and start|stop `timer` are _tiny_. 🔍 
Definitely wouldn't ship this. _You_ wouldn't use it. Neither would I. 😕 

Let's take a look at this together on the call on Monday morning. 🙏 
@iteles if you want to contribute, please be on Standup 09:30. 🕤

**Comment by LuchoTurtle** [comment]
Made changes according to the feedback.

I just wanted to note that there aren't any "buttons for "toggling" the item. The checkbox is merely an icon and the user can toggle the item by pressing anywhere within the area of the item container.

**Comment by nelsonic** [comment]
@LuchoTurtle thanks for the _correction_ about the lack of `<button>` to for checking the `item` as `done`. 🎉 
I feel like you're focussing on the wrong word in my previous comment ... 😕 

Maybe I can make this a little clearer: On the `iPhone SE` Simulator _everything_ on the page is _way_ too small:

Simulator Screenshot - iPhone SE (3rd generation) - 2023-04-05 at 08 21 46

The `text` is _tiny_. The Timer is barely legible. The checkbox _looks_ like it's less than `20 pixels` (width/height)
Yep hard-coded to `18`: 

https://github.com/dwyl/flutter-bloc-tutorial/blob/5338fe4df70212cc8f3a4e17326ca057c6340895/lib/main.dart#L194

No proportionality to the size of the screen. So on a bigger device like a `iPhone 14 Pro Max` it's even more comically tiny: 

Simulator Screenshot - iPhone 14 Pro Max - 2023-04-05 at 08 28 28

I feel like you you are focussing on nitpicking my ***words*** 
instead of trying your best to make the UI/UX the _best_ it can be. 
I _understand_ target area for the checkbox. 
You need to understand that when a reviewer gives you polite feedback it means "***fix it***"
not attempt to _correct/educate_ the reviewer. 

If you don't want to do the work. Please just let me know. 🙏 
If the purpose of this PR is to try and match the Figma design ....

Simulator Screenshot - iPhone 14 Pro Max - 2023-04-05 at 08 28 28

image

How closely do these two images match? 🤷‍♂️ 
Do I need to play a game of "Spot the Difference" and list all the ways they don't match? ⏳ 
Feels like my time (and that of any other reader) is being _wasted_ here ... 💸 🔥 

Video recording of my experience:
https://user-images.githubusercontent.com/194400/230009665-04d387ed-6cac-489e-aca8-3e8a3e364482.mp4

**Comment by LuchoTurtle** [comment]
I'll look more into it. Didn't mean to nitpick. I use my OnePlus 6T as a reference for "small devices" and I *thought* the dimensions of the widgets looked fine but I'll have an emulator downloaded to get this as close as possible.

> Unless otherwise stated we will target the iPhone SE (8/7/6) form factor

**Comment by LuchoTurtle** [comment]
I'm having this super annoying error that *only occurs during tests* and not on an iPhone SE device (even when I try to change resolution)...

```
A RenderFlex overflowed by 24 pixels on the bottom.
```

I can't properly debug *where exactly* this overflow is occurring because everything works fine when emulating.
I've [tried using `Expanded`, `Flexible` and wrapping widgets in `Containers` with specific dimensions](https://www.appsloveworld.com/flutter/100/29/renderflex-overflowed-error-only-appears-in-the-widget-test-if-i-run-the-app-eve) but nothing is working.

I've thought that it was perhaps the `Textfield` of the Homepage that was overflowing but even by wrapping both the `Textfield` and the `ItemsList` with `Expanded` widgets, it doesn't work...

**Comment by LuchoTurtle** [comment]
This error seems to have been introduced in [dwyl/flutter-bloc-tutorial@`53e91cc` (#3)](https://github.com/dwyl/flutter-bloc-tutorial/pull/3/commits/53e91cc4031cb81209d7b2ce5e5854f3793d8110)...

**Comment by LuchoTurtle** [comment]
This is what it looks like now.

https://user-images.githubusercontent.com/17494745/230126888-022f3043-7e4f-40e0-960d-c81e655ab496.mov

**Review by nelsonic — APPROVED** [review]
@LuchoTurtle thanks for making those updates. 👌 

I made a few _minor_ tweaks just to confirm my understanding of the code:

Simulator Screenshot - iPhone SE (3rd generation) - 2023-04-11 at 09 47 51

Merging as this is complete. ✅

**Comment by LuchoTurtle** [comment]
@nelsonic thank you for reviewing and making the tweaks. However, with those, Codecov is complaining the coverage went down :/
Could have assigned it back to me to fix the coverage before merging 👍

**Comment by nelsonic** [comment]
We will be adding to this example shortly. #4 
Please take a look at the coverage when you deploy using GH Pages. 🙏

**Pull request merged**
